config/routes.rb
Rails.application.routes.draw do
  resources :cat_rental_requests

  resources :cats
end

app/models/cat.rb
class Cat < ActiveRecord::Base
  COLORS = %w(black white grey orange brown red)
  validates :birth_date, :name, :sex, :color, presence: true
  validates :color, inclusion: { in: COLORS }
  validates :sex, inclusion: { in: %w(M F) }

  has_many :cat_rental_requests,
  :dependent => :destroy

  def age
    @age = Date.today - self.birth_date
    @age
  end

  def colors
    COLORS
  end
end

app/models/cat_rental_request.rb
class CatRentalRequest < ActiveRecord::Base
  validates :cat_id, :start_date, :end_date, :status, presence: true
  validates :status, inclusion: { in: %w(PENDING APPROVED DENIED) }
  # validates :overlapping_approved_requests

  belongs_to :cat

  # CatRentalRequest.find_by_cat_id

  # def overlapping_requests(request2)
  #   s1, e1 = self.start_date, self.end_date
  #   s2, e2 = request2.start_date, request2.end_date
  #
  #   s2 < e1 && s1 < s2 || s2 < s1 && s1 < e2
  # end
  #
  # def overlapping_approved_requests(request2)
  #   errors << "no no no" if self.overlapping_requests(request2) &&
  #     (self.status == APPROVED || request2.status == APPROVED)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  # protect_from_forgery with: :exception
end

app/controllers/cat_rental_requests_controller.rb
class CatRentalRequestsController < ApplicationController
  before_action :set_cat_rental_request, only: [:show, :edit, :update, :destroy]

  # GET /cat_rental_requests
  # GET /cat_rental_requests.json
  def index
    @cat_rental_requests = CatRentalRequest.all
  end

  # GET /cat_rental_requests/1
  # GET /cat_rental_requests/1.json
  def show
  end

  # GET /cat_rental_requests/new
  def new
    @cat_rental_request = CatRentalRequest.new
  end

  # GET /cat_rental_requests/1/edit
  def edit
  end

  # POST /cat_rental_requests
  # POST /cat_rental_requests.json
  def create
    @cat_rental_request = CatRentalRequest.new(cat_rental_request_params)

    respond_to do |format|
      if @cat_rental_request.save
        format.html { redirect_to @cat_rental_request, notice: 'Cat rental request was successfully created.' }
        format.json { render :show, status: :created, location: @cat_rental_request }
      else
        format.html { render :new }
        format.json { render json: @cat_rental_request.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cat_rental_requests/1
  # PATCH/PUT /cat_rental_requests/1.json
  def update
    respond_to do |format|
      if @cat_rental_request.update(cat_rental_request_params)
        format.html { redirect_to @cat_rental_request, notice: 'Cat rental request was successfully updated.' }
        format.json { render :show, status: :ok, location: @cat_rental_request }
      else
        format.html { render :edit }
        format.json { render json: @cat_rental_request.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cat_rental_requests/1
  # DELETE /cat_rental_requests/1.json
  def destroy
    @cat_rental_request.destroy
    respond_to do |format|
      format.html { redirect_to cat_rental_requests_url, notice: 'Cat rental request was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cat_rental_request
      @cat_rental_request = CatRentalRequest.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cat_rental_request_params
      params.fetch(:cat_rental_request, {})
    end
end

app/controllers/cats_controller.rb
class CatsController < ApplicationController
  def index
    @cats = Cat.all
    render :index
  end

  def show
    @cat = Cat.find(params[:id])
    # @cat_name = @cat.name
    render :show
  end

  def new
    @cat = Cat.new
    render :new
  end

  def edit
    @cat = Cat.find(params[:id])
    render :edit
  end

  def create
    @cat = Cat.create!(cat_params)
    if @cat.save
      redirect_to cat_url(@cat)
    else
      redirect_to cats_url
    end
  end

  def update
    @cat = Cat.find(params[:id])
    @cat.update!(cat_params)
    redirect_to cats_url
  end

  private

  def cat_params
    params.require(:cat).permit(:birth_date, :color, :text, :sex, :name)
  end



end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cat_rental_requests_helper.rb
module CatRentalRequestsHelper
end

app/helpers/cats_controller_helper.rb
module CatsControllerHelper
end

app/views/cat_rental_requests/_form.html.erb
<%= form_for(@cat_rental_request) do |f| %>
  <% if @cat_rental_request.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cat_rental_request.errors.count, "error") %> prohibited this cat_rental_request from being saved:</h2>

      <ul>
      <% @cat_rental_request.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/cat_rental_requests/edit.html.erb
<h1>Editing Cat Rental Request</h1>

<%= render 'form' %>

<%= link_to 'Show', @cat_rental_request %> |
<%= link_to 'Back', cat_rental_requests_path %>

app/views/cat_rental_requests/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Cat Rental Requests</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cat_rental_requests.each do |cat_rental_request| %>
      <tr>
        <td><%= link_to 'Show', cat_rental_request %></td>
        <td><%= link_to 'Edit', edit_cat_rental_request_path(cat_rental_request) %></td>
        <td><%= link_to 'Destroy', cat_rental_request, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cat rental request', new_cat_rental_request_path %>

app/views/cat_rental_requests/new.html.erb
<h1>New Cat Rental Request</h1>

<%= render 'form' %>

<%= link_to 'Back', cat_rental_requests_path %>

app/views/cat_rental_requests/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_cat_rental_request_path(@cat_rental_request) %> |
<%= link_to 'Back', cat_rental_requests_path %>

app/views/cats/_form.html.erb
<% if cat.persisted? %>
  <form action ="/cats/<%=cat.id%>" method="POST">
    <input type="hidden" name="_method" value="PATCH">
<% else %>
  <form action ="/cats" method="POST">
<% end %>

  <label for="cat_name">name</label>
  <input name="cat[name]" id="cat_name" type="text" value= "<%= cat.name %>">
  <br>

  <label>Sexytime</label>
  <div>
    <input name="cat[sex]" id="cat_sex_m" type="radio" value="M"
      <% if cat.sex == 'M' %>
        checked
      <% end %>
    >
    <label for="cat_sex_m">Male</label>

    <input name="cat[sex]" id="cat_sex_f" type="radio" value="F"
      <% if cat.sex == 'F' %>
        checked
      <% end %>
    >
    <label for="cat_sex_f">Female</label>


  </div>
  <br>

  <label for="cat_memories">Memories</label>
  <textarea name="cat[text]" id="cat_text"><%= cat.text %></textarea>
  <br>

  <label for="cat_color">Cat Color</label>
  <select name="cat[color]">
      <% cat.colors.each do |color| %>
        <option value= <%= color %>
          <% if cat.color == color %>
            selected
          <% end %>
          > <%= color.capitalize %>
        </option>
      <% end %>

  </select>
  <br>

  <label for="cat_birth_date">Birth date</label>
  <input name="cat[birth_date]" id="cat_birth_date" type="date" value= "<%= cat.birth_date %>">

  <br>

  <input type="submit" value="Build my cat!">

</form>

app/views/cats/edit.html.erb
<h1>Edit Cat!</h1>

<%= render partial: "form", locals: {cat: @cat} %>

app/views/cats/index.html.erb
<h2>Cats</h2>

<ul>
  <% @cats.each do |cat| %>
    <li><%= cat.inspect %> <%= link_to "Edit me :)", edit_cat_url(cat.id) %></li>
  <% end %>
</ul>

<%= link_to "Create new cat!", new_cat_url %>

app/views/cats/new.html.erb
<h1>New Cat</h1>

<%= render partial: "form", locals: {cat: @cat} %>

app/views/cats/show.html.erb
<h2><%= @cat.name %></h2>

<table>
  <tr>
    <th>birth_date</th>
    <td> <%= @cat.birth_date %> </td>
  </tr>
  <tr>
    <th>color</th>
    <td> <%= @cat.color %> </td>
  </tr>
  <tr>
    <th>sex</th>
    <td> <%= @cat.sex %> </td>
  </tr>
  <tr>
    <th>description</th>
    <td> <%= @cat.text %> </td>
  </tr>
</table>

<%= link_to "Peruse our friendly felines", cats_url %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ninetyninecats</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>